### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by aubreywullschleger** [sharenc/prj-rev-bwfs-dasmoto#1]
Subtlety for errors! Make sure to use `/` (forward slashes) in your URLs for `href` and `src` attributes, as this is best practice.  See here for more info: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#File_paths

https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12
https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L18
https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L24

**Comment by sharenc** [comment]
Thanks - noted and fixed.
