### ISSUE TITLE
id attribute syntax

### ISSUE THREAD

**Issue by aubreywullschleger** [sharenc/prj-rev-bwfs-dasmoto#2]
Subtlety for errors!  Make sure you are using correct syntax for `id` attributes.  The syntax you should use is:
`id="Value"`

instead of:
`id "Value"`

https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10
https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L16
https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L22

**Comment by sharenc** [comment]
Thanks - noted and fixed
