### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [sharenc/prj-rev-bwfs-dasmoto#3]
Great! Awesome job using locally stored images for your project! This is best practice for production code and helps your page load faster. 

Example: https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12

Also, I would make sure to use descriptive `alt` attributes on your `<img>` elements, like this: `<img src="./Resources/Images/hacksaw.jpg" alt="image of hacksaw paint brushes"/>`. This is best practice and helps make your site to be more accessible!

**Comment by sharenc** [comment]
Great tip - thanks
