### ISSUE TITLE
Nesting and indentation in HTML

### ISSUE THREAD

**Issue by aubreywullschleger** [sharenc/prj-rev-bwfs-dasmoto#4]
Great! Nice work using consistent nesting and indentation in your HTML. I also appreciate that you used `<div>` elements to wrap the different sections of your page. These practices help keep your markup organized and easy to read.

https://github.com/sharenc/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10-L27

**Comment by sharenc** [comment]
Thank you for the encouraging feedback.
